# Generated by Django 5.2.1 on 2025-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分组名称，例如：手术医师组')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('scope_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='作用域类型：DEPARTMENT、MODULE、SYSTEM')),
                ('scope_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='作用域的具体ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('creator_id', models.CharField(max_length=255, verbose_name='创建者id')),
            ],
            options={
                'verbose_name': '分组表',
                'verbose_name_plural': '分组表',
                'db_table': 't_group',
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, verbose_name='分组id')),
                ('permission_id', models.CharField(max_length=255, verbose_name='权限id')),
            ],
            options={
                'db_table': 't_group_permission',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, verbose_name='分组id')),
                ('user_id', models.CharField(max_length=255, verbose_name='用户id')),
            ],
            options={
                'db_table': 't_group_user',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='权限描述')),
                ('route', models.CharField(max_length=255, verbose_name='对应的系统路由或模块')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='查看术前访视列表：previsit:get，术前访视评估：previsit:evaluate')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('dn', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='性别')),
                ('name', models.CharField(blank=True, max_length=95, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=95, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='职位')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('DELETED', '删除'), ('INACTIVE', '停用')], default='NORMAL', max_length=255, verbose_name='状态')),
                ('user_type', models.CharField(choices=[('ADMINISTRATOR', '系统管理员'), ('USER', '普通用户')], default='USER', max_length=255, verbose_name='用户类型')),
                ('username', models.CharField(max_length=95, unique=True, verbose_name='用户名')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户openai的key值')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='2FA的密钥')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='UserExternal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255, verbose_name='名(first_name)')),
                ('last_name', models.CharField(max_length=255, verbose_name='姓(last_name)')),
                ('display_name', models.CharField(max_length=255, verbose_name='显示名(full_name)')),
                ('ou', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属组织单位')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联的用户id')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AD用户拓展表',
                'verbose_name_plural': 'AD用户拓展表',
                'db_table': 't_user_external',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='用户id')),
                ('permission_id', models.CharField(max_length=255, verbose_name='权限id')),
            ],
            options={
                'db_table': 't_user_permission',
            },
        ),
    ]
